// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShirlyStudio.Models;

namespace ShirlyStudio.Migrations
{
    [DbContext(typeof(ShirlyStudioContext))]
    [Migration("20180912211316_InitailNew")]
    partial class InitailNew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShirlyStudio.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ShirlyStudio.Models.WorkshopCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<int>("WorkshopId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("WorkshopCategory");
                });

            modelBuilder.Entity("WebApplication4.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("WebApplication4.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("WebApplication4.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CustomerIdId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerIdId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("WebApplication4.Models.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Available_Members");

                    b.Property<string>("Description");

                    b.Property<DateTime>("FullData");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<int?>("TeacherIdId");

                    b.Property<int?>("TransactionIdId");

                    b.HasKey("Id");

                    b.HasIndex("TeacherIdId");

                    b.HasIndex("TransactionIdId");

                    b.ToTable("Workshop");
                });

            modelBuilder.Entity("ShirlyStudio.Models.WorkshopCategory", b =>
                {
                    b.HasOne("ShirlyStudio.Models.Category", "Category")
                        .WithMany("WorkshopCategory")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApplication4.Models.Workshop", "Workshop")
                        .WithMany("WorkshopCategory")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApplication4.Models.Transaction", b =>
                {
                    b.HasOne("WebApplication4.Models.Customer", "CustomerId")
                        .WithMany("Transaction")
                        .HasForeignKey("CustomerIdId");
                });

            modelBuilder.Entity("WebApplication4.Models.Workshop", b =>
                {
                    b.HasOne("WebApplication4.Models.Teacher", "TeacherId")
                        .WithMany("Workshops")
                        .HasForeignKey("TeacherIdId");

                    b.HasOne("WebApplication4.Models.Transaction", "TransactionId")
                        .WithMany("Workshop")
                        .HasForeignKey("TransactionIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
